name: Update PR Preview Link

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: read

jobs:
  update-preview-link:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR description with preview link
        uses: actions/github-script@v7
        with:
          script: |
            const PLACEHOLDER = '{PR_NUMBER}';
            const prNumber = context.payload.pull_request.number;
            const prBody = context.payload.pull_request.body || '';
            
            // Check if the PR body contains the placeholder
            if (prBody.includes(PLACEHOLDER)) {
              const updatedBody = prBody.replace(
                new RegExp(PLACEHOLDER, 'g'), 
                prNumber
              );
              
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                body: updatedBody
              });
              
              console.log(`Updated PR #${prNumber} preview link`);
            } else {
              console.log(`PR #${prNumber} description doesn't contain {PR_NUMBER} placeholder`);
            }
